epochs: 5
batch_size: 75
supervised: false
normalize_with_sigmoid: false
learning_rate: 0.001
weight_decay: 0.0001
temperature: 0.1
first_hidden_dim: 256
gru_residual_dim: 128
final_dim: 4
lstm_dims: [256, 128, 64]
dense_layer: 128
output_dim: 32